<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FU6I2BF" ignored="0" name="Test" tests="7" failures="1" timestamp="2019-09-27T03:14:55 PDT" time="0.065" errors="0">
  <testcase name="method3" time="0.006" classname="LearnTestNG.DemoB">
    <failure type="java.lang.AssertionError" message="I am method no3 and I will Fail!">
      <![CDATA[java.lang.AssertionError: I am method no3 and I will Fail!
at LearnTestNG.DemoB.method3(DemoB.java:29)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
  <testcase name="method1" time="0.001" classname="LearnTestNG.DemoB"/>
  <testcase name="method1" time="0.001" classname="LearnTestNG.DemoB"/>
  <testcase name="method1" time="0.001" classname="LearnTestNG.DemoB"/>
  <testcase name="method5" time="0.001" classname="LearnTestNG.DemoB"/>
  <testcase name="method5" time="0.001" classname="LearnTestNG.DemoB"/>
  <testcase name="method4" time="0.0" classname="LearnTestNG.DemoB">
    <skipped/>
  </testcase> <!-- method4 -->
</testsuite> <!-- Test -->
